version: "3.8"

services:
  mrb-portal:
    build: .
    environment:
      PORT: "8088"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-1537}"
    ports:
      - "8088:8088"
    volumes:
      - mrb_portal_data:/app/data
      - mrb_portal_uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  mrb_portal_data:
  mrb_portal_uploads:
